version: '3.8'
services:
  redis:
    image: redis:7

  web:
    build: .
    ports:
      - "7777:7777" # flask
      - "3920:3920" # debugpy
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development 
    command: python -m debugpy --listen 0.0.0.0:3920 --wait-for-client -m flask run --host=0.0.0.0 --port=7777
    depends_on:
      - redis

  celery:
    build: .
    volumes:
      - .:/app
    command: celery -A tasks.celery worker --loglevel=info
    depends_on:
      - redis