version: '3.8'
services:
  redis:
    image: redis:7

  web:
    build: .
    ports:
      - "7777:7777"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development 
    command: flask run --host=0.0.0.0 --port=7777
    depends_on:
      - redis

  celery:
    build: .
    volumes:
      - .:/app
    command: celery -A tasks.celery worker --loglevel=info
    depends_on:
      - redis